baseURL = "/"
languageCode = "en-us"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    style = "dracula"
    tabWidth = 2
