[build]
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.89.4"
  NODE_VERSION = "16.6.0"
  YARN_VERSION = "1.22.17"
  NETLIFY_USE_YARN = "true"

[context.production]
  command = "hugo -b $URL --gc --minify"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"
